# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1
orbs:
  snyk: snyk/snyk@2.3 # https://circleci.com/developer/orbs/orb/snyk/snyk

jobs:
  # Snyk implementation for repos not in PD Org.
  snyk_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - snyk/install
      - run: snyk config set org='rundeck-core-mtgfa3XPaKGbFtHj9aRXhg'
      - run:
          name: Run Snyk monitors to track vulnerabilities on main only
          command: |
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              snyk monitor buildSrc --detection-depth=10
            else
              echo "Skipping monitor for non-main branch - no data sent to dashboard"
            fi
      - run: snyk test buildSrc --detection-depth=10 || true # only scan buildSrc.

workflows:
  version: 2
  snyk_security:
    jobs:
      - snyk_test:
          context:
            - Snyk